'use strict';

var index = require('../index-87a1c908.js');

/* src/components/ProjectTile.svelte generated by Svelte v3.35.0 */

const ProjectTile = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { project } = $$props;

	let link = project.frontmatter.externalLink
	? project.frontmatter.externalLink
	: `/project/${project.slug}`;

	if ($$props.project === void 0 && $$bindings.project && project !== void 0) $$bindings.project(project);

	return `<div class="${"project"}"><a${index.add_attribute("href", link, 0)} class="${"link"}"><img${index.add_attribute("src", project.frontmatter.logo, 0)} alt="${index.escape(project.frontmatter.title) + " project thumbnail"}" class="${"thumbnail"}">
    <div class="${"ui-overlay -fallback"}"><strong>${index.escape(project.frontmatter.title)}</strong>
      ${index.escape(project.frontmatter.type)}</div></a></div>`;
});

module.exports = ProjectTile;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/components/ProjectTile.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUHJvamVjdFRpbGUuanMiLCJzb3VyY2VzIjpbIi4uLy4uLy4uL3NyYy9jb21wb25lbnRzL1Byb2plY3RUaWxlLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBleHBvcnQgbGV0IHByb2plY3Q7XG4gIGxldCBsaW5rID0gcHJvamVjdC5mcm9udG1hdHRlci5leHRlcm5hbExpbmtcbiAgICA/IHByb2plY3QuZnJvbnRtYXR0ZXIuZXh0ZXJuYWxMaW5rXG4gICAgOiBgL3Byb2plY3QvJHtwcm9qZWN0LnNsdWd9YDtcbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwicHJvamVjdFwiPlxuICA8YSBocmVmPVwie2xpbmt9XCIgY2xhc3M9XCJsaW5rXCI+XG4gICAgPGltZ1xuICAgICAgc3JjPVwie3Byb2plY3QuZnJvbnRtYXR0ZXIubG9nb31cIlxuICAgICAgYWx0PVwie3Byb2plY3QuZnJvbnRtYXR0ZXIudGl0bGV9IHByb2plY3QgdGh1bWJuYWlsXCJcbiAgICAgIGNsYXNzPVwidGh1bWJuYWlsXCJcbiAgICAvPlxuICAgIDxkaXYgY2xhc3M9XCJ1aS1vdmVybGF5IC1mYWxsYmFja1wiPlxuICAgICAgPHN0cm9uZz57cHJvamVjdC5mcm9udG1hdHRlci50aXRsZX08L3N0cm9uZz5cbiAgICAgIHtwcm9qZWN0LmZyb250bWF0dGVyLnR5cGV9XG4gICAgPC9kaXY+XG4gIDwvYT5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7T0FDYSxPQUFPOztLQUNkLElBQUksR0FBRyxPQUFPLENBQUMsV0FBVyxDQUFDLFlBQUE7R0FDM0IsT0FBTyxDQUFDLFdBQVcsQ0FBQyxZQUFBO2VBQ1IsT0FBTyxDQUFDLElBQUk7Ozs7bUVBSWxCLElBQUkseURBRUosT0FBTyxDQUFDLFdBQVcsQ0FBQyxJQUFJLDBCQUN4QixPQUFPLENBQUMsV0FBVyxDQUFDLEtBQUs7a0VBSXRCLE9BQU8sQ0FBQyxXQUFXLENBQUMsS0FBSztxQkFDakMsT0FBTyxDQUFDLFdBQVcsQ0FBQyxJQUFJOzs7OzsifQ==
