'use strict';

var index = require('../../index-87a1c908.js');

/* src/routes/simple/Simple.svelte generated by Svelte v3.29.7 */

const css = {
	code: "a.svelte-5i6b92{margin-bottom:1rem;display:inline-block}",
	map: "{\"version\":3,\"file\":\"Simple.svelte\",\"sources\":[\"Simple.svelte\"],\"sourcesContent\":[\"<script>\\n  export let data, helpers;\\n</script>\\n\\n<style>\\n  a {\\n    margin-bottom: 1rem;\\n    display: inline-block;\\n  }\\n/*# sourceMappingURL=src/routes/simple/Simple.svelte.map */</style>\\n\\n<svelte:head>\\n  <title>{data.title}</title>\\n</svelte:head>\\n\\n<a href=\\\"/\\\">&LeftArrow; Home</a>\\n\\n<h1>{data.title}</h1>\\n\\n<ul>\\n  {#each data.steps as step}\\n    <li>{step}</li>\\n  {/each}\\n</ul>\\n\\n{@html data.content}\\n\"],\"names\":[],\"mappings\":\"AAKE,CAAC,cAAC,CAAC,AACD,aAAa,CAAE,IAAI,CACnB,OAAO,CAAE,YAAY,AACvB,CAAC\"}"
};

const Simple = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props, { helpers } = $$props;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	if ($$props.helpers === void 0 && $$bindings.helpers && helpers !== void 0) $$bindings.helpers(helpers);
	$$result.css.add(css);

	return `${($$result.head += `${($$result.title = `<title>${index.escape(data.title)}</title>`, "")}`, "")}

<a href="${"/"}" class="${"svelte-5i6b92"}">← Home</a>

<h1>${index.escape(data.title)}</h1>

<ul>${index.each(data.steps, step => `<li>${index.escape(step)}</li>`)}</ul>

${data.content}`;
});

module.exports = Simple;
module.exports._css = "a.svelte-5i6b92{margin-bottom:1rem;display:inline-block}";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9zcmMvc3JjL3NyYy9zcmMvc3JjL3NyYy9zcmMvc3JjL3NyYy9zcmMvc3JjL3NyYy9zcmMvc3JjL3NyYy9zcmMvc3JjL3NyYy9zcmMvc3JjL3JvdXRlcy9zaW1wbGUvU2ltcGxlLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFLRyxnQkFBRSxjQUNjLEtBQ2YsUUFBUyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgZGF0YSwgaGVscGVycztcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIGEge1xuICAgIG1hcmdpbi1ib3R0b206IDFyZW07XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICB9XG4vKiMgc291cmNlTWFwcGluZ1VSTD1zcmMvcm91dGVzL3NpbXBsZS9TaW1wbGUuc3ZlbHRlLm1hcCAqLzwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPntkYXRhLnRpdGxlfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48YSBocmVmPVwiL1wiPiZMZWZ0QXJyb3c7IEhvbWU8L2E+XG5cbjxoMT57ZGF0YS50aXRsZX08L2gxPlxuXG48dWw+XG4gIHsjZWFjaCBkYXRhLnN0ZXBzIGFzIHN0ZXB9XG4gICAgPGxpPntzdGVwfTwvbGk+XG4gIHsvZWFjaH1cbjwvdWw+XG5cbntAaHRtbCBkYXRhLmNvbnRlbnR9XG4iXX0= *\u002F";
module.exports._cssIncluded = ["src/routes/simple/Simple.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2ltcGxlLmpzIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zcmMvcm91dGVzL3NpbXBsZS9TaW1wbGUuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgZGF0YSwgaGVscGVycztcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIGEge1xuICAgIG1hcmdpbi1ib3R0b206IDFyZW07XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT57ZGF0YS50aXRsZX08L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGEgaHJlZj1cIi9cIj4mTGVmdEFycm93OyBIb21lPC9hPlxuXG48aDE+e2RhdGEudGl0bGV9PC9oMT5cblxuPHVsPlxuICB7I2VhY2ggZGF0YS5zdGVwcyBhcyBzdGVwfVxuICAgIDxsaT57c3RlcH08L2xpPlxuICB7L2VhY2h9XG48L3VsPlxuXG57QGh0bWwgZGF0YS5jb250ZW50fVxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7OztPQUNhLElBQUksZ0JBQUUsT0FBTzs7Ozs7eUVBV2hCLElBQUksQ0FBQyxLQUFLOzs7O21CQUtmLElBQUksQ0FBQyxLQUFLOztpQkFHTixJQUFJLENBQUMsS0FBSyw4QkFDVixJQUFJOztFQUlOLElBQUksQ0FBQyxPQUFPOzs7OzsifQ==
