'use strict';

var index = require('../index-87a1c908.js');

/* src/layouts/Layout.svelte generated by Svelte v3.35.0 */

const Layout = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { templateHtml } = $$props, { settings } = $$props;
	if ($$props.templateHtml === void 0 && $$bindings.templateHtml && templateHtml !== void 0) $$bindings.templateHtml(templateHtml);
	if ($$props.settings === void 0 && $$bindings.settings && settings !== void 0) $$bindings.settings(settings);

	return `${($$result.head += `<meta name="${"viewport"}" content="${"width=device-width, initial-scale=1"}" data-svelte="svelte-1w9ch23"><link href="${"https://fonts.googleapis.com/css?family=Nunito:400,800&display=swap"}" rel="${"stylesheet"}" data-svelte="svelte-1w9ch23"><link rel="${"stylesheet"}" href="${"/main.css"}" data-svelte="svelte-1w9ch23"><link rel="${"stylesheet"}" href="${"/style.css"}" data-svelte="svelte-1w9ch23">`, "")}

${templateHtml}`;
});

module.exports = Layout;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/layouts/Layout.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTGF5b3V0LmpzIiwic291cmNlcyI6WyIuLi8uLi8uLi9zcmMvbGF5b3V0cy9MYXlvdXQuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgdGVtcGxhdGVIdG1sLCBzZXR0aW5ncztcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MVwiPlxuICA8bGluayBocmVmPVwiaHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M/ZmFtaWx5PU51bml0bzo0MDAsODAwJmRpc3BsYXk9c3dhcFwiIHJlbD1cInN0eWxlc2hlZXRcIj5cbiAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCIvbWFpbi5jc3NcIj5cbiAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCIvc3R5bGUuY3NzXCI+XG48L3N2ZWx0ZTpoZWFkPlxuXG57QGh0bWwgdGVtcGxhdGVIdG1sfVxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7T0FDYSxZQUFZLGdCQUFFLFFBQVE7Ozs7OztFQVU1QixZQUFZOzs7OzsifQ==
