'use strict';

var index = require('../../index-87a1c908.js');

/* src/routes/work/Work.svelte generated by Svelte v3.35.0 */

const Work = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props; // data is mainly being populated from the /plugins/edlerjs-plugin-markdown/index.js
	const { html, frontmatter } = data;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${($$result.head += `${($$result.title = `<title>Simon Layfield | Work</title>`, "")}`, "")}

<div class="${"ui-container"}">${html}</div>`;
});

module.exports = Work;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/routes/work/Work.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiV29yay5qcyIsInNvdXJjZXMiOlsiLi4vLi4vLi4vLi4vc3JjL3JvdXRlcy93b3JrL1dvcmsuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgZGF0YTsgLy8gZGF0YSBpcyBtYWlubHkgYmVpbmcgcG9wdWxhdGVkIGZyb20gdGhlIC9wbHVnaW5zL2VkbGVyanMtcGx1Z2luLW1hcmtkb3duL2luZGV4LmpzXG4gIGNvbnN0IHsgaHRtbCwgZnJvbnRtYXR0ZXIgfSA9IGRhdGE7XG5cbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TaW1vbiBMYXlmaWVsZCB8IFdvcms8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGRpdiBjbGFzcz1cInVpLWNvbnRhaW5lclwiPlxuICB7QGh0bWwgaHRtbH1cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7T0FDYSxJQUFJO1NBQ1AsSUFBSSxFQUFFLFdBQVcsS0FBSyxJQUFJOzs7OztpQ0FTM0IsSUFBSTs7Ozs7In0=
